In [68]:
import torch
from models.networks.generator import ResNet34Generator

opt = type(str(), tuple(), dict())
opt.transfer_weights = "/data/natsuki/dataset_atmaCup11/checkpoints/atma11simple_xavier_3fold0/5_net_G.pth"
opt.transfer_freeze = True
opt.out_features = 1
model = ResNet34Generator(opt)


Parameter containing:
tensor([[[[ 0.0280, -0.0232,  0.0184,  ..., -0.0660, -0.0425,  0.0362],
          [-0.0171, -0.0016, -0.0532,  ..., -0.0667, -0.0142, -0.0285],
          [-0.0116,  0.0538,  0.0074,  ...,  0.0081, -0.0018,  0.0230],
          ...,
          [ 0.0169,  0.0069, -0.0056,  ...,  0.0086, -0.0044, -0.0281],
          [ 0.0325,  0.0190, -0.0114,  ..., -0.0403,  0.0268, -0.0326],
          [-0.0052,  0.0277, -0.0377,  ..., -0.0121,  0.0006, -0.0271]],

         [[ 0.0251,  0.0345, -0.0108,  ...,  0.0081,  0.0316, -0.0209],
          [ 0.0096,  0.0289, -0.0308,  ..., -0.0501, -0.0035,  0.0128],
          [-0.0367,  0.0427, -0.0150,  ...,  0.0204, -0.0074,  0.0051],
          ...,
          [-0.0400,  0.0068, -0.0231,  ...,  0.0177,  0.0337,  0.0831],
          [-0.0025, -0.0073,  0.0022,  ..., -0.0212,  0.0304, -0.0036],
          [-0.0125,  0.0318,  0.0554,  ..., -0.0016,  0.0383,  0.0233]],

         [[-0.0087,  0.0411, -0.0259,  ..., -0.0163,  0.0285, -0.0279],
        

In [ ]:
def check_freeze(model):
    top =  list(model.parameters())[0]
    btm = model.model.fc.bias
    print( top.requires_grad , top[0,0,0,0])
    print( btm.requires_grad , btm[0])

In [69]:
save_path = "/data/natsuki/dataset_atmaCup11/checkpoints/atma11simple_xavier_3fold0/5_net_G.pth"
weights = torch.load(save_path)
print()

Parameter containing:
tensor([[[[ 0.0280, -0.0232,  0.0184,  ..., -0.0660, -0.0425,  0.0362],
          [-0.0171, -0.0016, -0.0532,  ..., -0.0667, -0.0142, -0.0285],


In [61]:
save_path = "/data/natsuki/dataset_atmaCup11/checkpoints/atma11simple_tranfer_freeze_debug/1_net_G.pth"
weights = torch.load(save_path)
print("\n".join(str(weights["model.conv1.weight"]).split("\n")[:3]))

tensor([[[[ 1.0851e-03, -2.5813e-04,  5.8428e-05,  ...,  2.1882e-04,
           -4.3204e-04,  3.0235e-04],
          [ 2.0752e-04, -1.1216e-04, -6.5656e-04,  ..., -1.7167e-04,


In [47]:
save_path = "/data/natsuki/dataset_atmaCup11/checkpoints/atma11simple_tranfer_freeze_debug/2_net_G.pth"
weights = torch.load(save_path)
model.load_state_dict(weights)
check_freeze(model)

False tensor(0.0011)
True tensor(0.0395, grad_fn=<SelectBackward>)


In [48]:
save_path = "/data/natsuki/dataset_atmaCup11/checkpoints/atma11simple_tranfer_freeze_debug/3_net_G.pth"
weights = torch.load(save_path)
model.load_state_dict(weights)
check_freeze(model)

False tensor(0.0011)
True tensor(0.0410, grad_fn=<SelectBackward>)


In [77]:

with open("/home/natsuki/hoge.log","a") as f:
    f.write(__file__, str(model.model.conv1.weight).split("\n")[1]+"\n")

NameError: name '__file__' is not defined

In [78]:
globals()

{'__name__': '__main__',
 '__doc__': 'Automatically created module for IPython interactive environment',
 '__package__': None,
 '__loader__': None,
 '__spec__': None,
 '__builtin__': <module 'builtins' (built-in)>,
 '__builtins__': <module 'builtins' (built-in)>,
 '_ih': ['',
  "get_ipython().run_line_magic('ls', '')",
  'from models.networks.generator import ResNet34Generator',
  'str()',
  'import torch\nfrom models.networks.generator import ResNet34Generator\n\nopt = type(str(), tuple(), dict())',
  'opt.transfer_weights = "/data/natsuki/dataset_atmaCup11/checkpoints/atma11simple_xavier_3fold0/5_net_G.pth"\nopt.transfer_freeze = True\nopt.out_features = 1',
  'import torch\nfrom models.networks.generator import ResNet34Generator\n\nopt = type(str(), tuple(), dict())\nopt.transfer_weights = "/data/natsuki/dataset_atmaCup11/checkpoints/atma11simple_xavier_3fold0/5_net_G.pth"\nopt.transfer_freeze = True\nopt.out_features = 1\nmodel = ResNet34Generator(opt)',
  'model',
  'model.model.f